# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Difi < Formula
  desc "The pixel-perfect terminal diff viewer"
  homepage "https://github.com/oug-t/difi"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oug-t/difi/releases/download/v0.0.1/difi_Darwin_x86_64.tar.gz"
      sha256 "19f81ab19ca1b3be83e0c936b1b36929644f1362ec655a52040aaf70558227de"

      def install
        bin.install "difi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oug-t/difi/releases/download/v0.0.1/difi_Darwin_arm64.tar.gz"
      sha256 "88c6d8c7895860a1d2d69eefacab430307bf4aa3a38a7affefe55e7fd85398c4"

      def install
        bin.install "difi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oug-t/difi/releases/download/v0.0.1/difi_Linux_x86_64.tar.gz"
      sha256 "0a0411eda3df236210586f560743b1702738ba04d34184bd3d733a112d527597"
      def install
        bin.install "difi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oug-t/difi/releases/download/v0.0.1/difi_Linux_arm64.tar.gz"
      sha256 "e0f9d239d1af4c3865211e8865b35748fd0120b0056d91578130c7c8902dfe20"
      def install
        bin.install "difi"
      end
    end
  end
end
