# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Difi < Formula
  desc "The pixel-perfect terminal diff viewer"
  homepage "https://github.com/oug-t/difi"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oug-t/difi/releases/download/v0.1.1/difi_Darwin_x86_64.tar.gz"
      sha256 "0f228a503578cf91b097a338924127a08f0de164344ad603c5cf9971ec4b1266"

      def install
        bin.install "difi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oug-t/difi/releases/download/v0.1.1/difi_Darwin_arm64.tar.gz"
      sha256 "2352386db10b1cd47d6fa9da4cfcb2129726f56b5f7d5f8816bbdd800c04660c"

      def install
        bin.install "difi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oug-t/difi/releases/download/v0.1.1/difi_Linux_x86_64.tar.gz"
      sha256 "ca78deccab6a055a356c3a57caf60296857f86f1f96544cfb5e59e9a32bdf040"
      def install
        bin.install "difi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oug-t/difi/releases/download/v0.1.1/difi_Linux_arm64.tar.gz"
      sha256 "42c71f83f052c1d26902f2ed3a305682e81e20d7f3628f5b2bc05b99035ed173"
      def install
        bin.install "difi"
      end
    end
  end
end
